# Generated by Django 5.2.8 on 2025-11-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VENTASAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='venta',
            unique_together={('tipo_documento', 'folio')},
        ),
    ]
