# Generated by Django 5.2.8 on 2025-12-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VENTASAPP', '0003_cliente_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='controldia',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
