# Generated by Django 5.2.8 on 2025-12-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VENTASAPP', '0004_controldia_hora_apertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(default='Efectivo', max_length=50),
        ),
    ]
